// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GodFather-server/ent/approval_information"
	"GodFather-server/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApprovalInformationDelete is the builder for deleting a Approval_information entity.
type ApprovalInformationDelete struct {
	config
	hooks    []Hook
	mutation *ApprovalInformationMutation
}

// Where adds a new predicate to the ApprovalInformationDelete builder.
func (aid *ApprovalInformationDelete) Where(ps ...predicate.Approval_information) *ApprovalInformationDelete {
	aid.mutation.predicates = append(aid.mutation.predicates, ps...)
	return aid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aid *ApprovalInformationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aid.hooks) == 0 {
		affected, err = aid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ApprovalInformationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aid.mutation = mutation
			affected, err = aid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aid.hooks) - 1; i >= 0; i-- {
			mut = aid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aid *ApprovalInformationDelete) ExecX(ctx context.Context) int {
	n, err := aid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aid *ApprovalInformationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: approval_information.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: approval_information.FieldID,
			},
		},
	}
	if ps := aid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aid.driver, _spec)
}

// ApprovalInformationDeleteOne is the builder for deleting a single Approval_information entity.
type ApprovalInformationDeleteOne struct {
	aid *ApprovalInformationDelete
}

// Exec executes the deletion query.
func (aido *ApprovalInformationDeleteOne) Exec(ctx context.Context) error {
	n, err := aido.aid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{approval_information.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aido *ApprovalInformationDeleteOne) ExecX(ctx context.Context) {
	aido.aid.ExecX(ctx)
}
