// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GodFather-server/ent/approval_information"
	"GodFather-server/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApprovalInformationQuery is the builder for querying Approval_information entities.
type ApprovalInformationQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.Approval_information
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApprovalInformationQuery builder.
func (aiq *ApprovalInformationQuery) Where(ps ...predicate.Approval_information) *ApprovalInformationQuery {
	aiq.predicates = append(aiq.predicates, ps...)
	return aiq
}

// Limit adds a limit step to the query.
func (aiq *ApprovalInformationQuery) Limit(limit int) *ApprovalInformationQuery {
	aiq.limit = &limit
	return aiq
}

// Offset adds an offset step to the query.
func (aiq *ApprovalInformationQuery) Offset(offset int) *ApprovalInformationQuery {
	aiq.offset = &offset
	return aiq
}

// Order adds an order step to the query.
func (aiq *ApprovalInformationQuery) Order(o ...OrderFunc) *ApprovalInformationQuery {
	aiq.order = append(aiq.order, o...)
	return aiq
}

// First returns the first Approval_information entity from the query.
// Returns a *NotFoundError when no Approval_information was found.
func (aiq *ApprovalInformationQuery) First(ctx context.Context) (*Approval_information, error) {
	nodes, err := aiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{approval_information.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) FirstX(ctx context.Context) *Approval_information {
	node, err := aiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Approval_information ID from the query.
// Returns a *NotFoundError when no Approval_information ID was found.
func (aiq *ApprovalInformationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{approval_information.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) FirstIDX(ctx context.Context) int {
	id, err := aiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Approval_information entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one Approval_information entity is not found.
// Returns a *NotFoundError when no Approval_information entities are found.
func (aiq *ApprovalInformationQuery) Only(ctx context.Context) (*Approval_information, error) {
	nodes, err := aiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{approval_information.Label}
	default:
		return nil, &NotSingularError{approval_information.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) OnlyX(ctx context.Context) *Approval_information {
	node, err := aiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Approval_information ID in the query.
// Returns a *NotSingularError when exactly one Approval_information ID is not found.
// Returns a *NotFoundError when no entities are found.
func (aiq *ApprovalInformationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = &NotSingularError{approval_information.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) OnlyIDX(ctx context.Context) int {
	id, err := aiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Approval_informations.
func (aiq *ApprovalInformationQuery) All(ctx context.Context) ([]*Approval_information, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) AllX(ctx context.Context) []*Approval_information {
	nodes, err := aiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Approval_information IDs.
func (aiq *ApprovalInformationQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := aiq.Select(approval_information.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) IDsX(ctx context.Context) []int {
	ids, err := aiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aiq *ApprovalInformationQuery) Count(ctx context.Context) (int, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) CountX(ctx context.Context) int {
	count, err := aiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aiq *ApprovalInformationQuery) Exist(ctx context.Context) (bool, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aiq *ApprovalInformationQuery) ExistX(ctx context.Context) bool {
	exist, err := aiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApprovalInformationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aiq *ApprovalInformationQuery) Clone() *ApprovalInformationQuery {
	if aiq == nil {
		return nil
	}
	return &ApprovalInformationQuery{
		config:     aiq.config,
		limit:      aiq.limit,
		offset:     aiq.offset,
		order:      append([]OrderFunc{}, aiq.order...),
		predicates: append([]predicate.Approval_information{}, aiq.predicates...),
		// clone intermediate query.
		sql:  aiq.sql.Clone(),
		path: aiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status approval_information.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApprovalInformation.Query().
//		GroupBy(approval_information.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aiq *ApprovalInformationQuery) GroupBy(field string, fields ...string) *ApprovalInformationGroupBy {
	group := &ApprovalInformationGroupBy{config: aiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aiq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status approval_information.Status `json:"status,omitempty"`
//	}
//
//	client.ApprovalInformation.Query().
//		Select(approval_information.FieldStatus).
//		Scan(ctx, &v)
//
func (aiq *ApprovalInformationQuery) Select(field string, fields ...string) *ApprovalInformationSelect {
	aiq.fields = append([]string{field}, fields...)
	return &ApprovalInformationSelect{ApprovalInformationQuery: aiq}
}

func (aiq *ApprovalInformationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aiq.fields {
		if !approval_information.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aiq.path != nil {
		prev, err := aiq.path(ctx)
		if err != nil {
			return err
		}
		aiq.sql = prev
	}
	return nil
}

func (aiq *ApprovalInformationQuery) sqlAll(ctx context.Context) ([]*Approval_information, error) {
	var (
		nodes   = []*Approval_information{}
		withFKs = aiq.withFKs
		_spec   = aiq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, approval_information.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &Approval_information{config: aiq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, aiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aiq *ApprovalInformationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aiq.querySpec()
	return sqlgraph.CountNodes(ctx, aiq.driver, _spec)
}

func (aiq *ApprovalInformationQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aiq *ApprovalInformationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   approval_information.Table,
			Columns: approval_information.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: approval_information.FieldID,
			},
		},
		From:   aiq.sql,
		Unique: true,
	}
	if fields := aiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approval_information.FieldID)
		for i := range fields {
			if fields[i] != approval_information.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, approval_information.ValidColumn)
			}
		}
	}
	return _spec
}

func (aiq *ApprovalInformationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aiq.driver.Dialect())
	t1 := builder.Table(approval_information.Table)
	selector := builder.Select(t1.Columns(approval_information.Columns...)...).From(t1)
	if aiq.sql != nil {
		selector = aiq.sql
		selector.Select(selector.Columns(approval_information.Columns...)...)
	}
	for _, p := range aiq.predicates {
		p(selector)
	}
	for _, p := range aiq.order {
		p(selector, approval_information.ValidColumn)
	}
	if offset := aiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApprovalInformationGroupBy is the group-by builder for Approval_information entities.
type ApprovalInformationGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aigb *ApprovalInformationGroupBy) Aggregate(fns ...AggregateFunc) *ApprovalInformationGroupBy {
	aigb.fns = append(aigb.fns, fns...)
	return aigb
}

// Scan applies the group-by query and scans the result into the given value.
func (aigb *ApprovalInformationGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aigb.path(ctx)
	if err != nil {
		return err
	}
	aigb.sql = query
	return aigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) StringsX(ctx context.Context) []string {
	v, err := aigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) StringX(ctx context.Context) string {
	v, err := aigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) IntsX(ctx context.Context) []int {
	v, err := aigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) IntX(ctx context.Context) int {
	v, err := aigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *ApprovalInformationGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aigb *ApprovalInformationGroupBy) BoolX(ctx context.Context) bool {
	v, err := aigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aigb *ApprovalInformationGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aigb.fields {
		if !approval_information.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aigb *ApprovalInformationGroupBy) sqlQuery() *sql.Selector {
	selector := aigb.sql
	columns := make([]string, 0, len(aigb.fields)+len(aigb.fns))
	columns = append(columns, aigb.fields...)
	for _, fn := range aigb.fns {
		columns = append(columns, fn(selector, approval_information.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(aigb.fields...)
}

// ApprovalInformationSelect is the builder for selecting fields of ApprovalInformation entities.
type ApprovalInformationSelect struct {
	*ApprovalInformationQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ais *ApprovalInformationSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ais.prepareQuery(ctx); err != nil {
		return err
	}
	ais.sql = ais.ApprovalInformationQuery.sqlQuery(ctx)
	return ais.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ais *ApprovalInformationSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ais.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ais *ApprovalInformationSelect) StringsX(ctx context.Context) []string {
	v, err := ais.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ais.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ais *ApprovalInformationSelect) StringX(ctx context.Context) string {
	v, err := ais.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ais *ApprovalInformationSelect) IntsX(ctx context.Context) []int {
	v, err := ais.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ais.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ais *ApprovalInformationSelect) IntX(ctx context.Context) int {
	v, err := ais.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ais *ApprovalInformationSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ais.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ais.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ais *ApprovalInformationSelect) Float64X(ctx context.Context) float64 {
	v, err := ais.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: ApprovalInformationSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ais *ApprovalInformationSelect) BoolsX(ctx context.Context) []bool {
	v, err := ais.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ais *ApprovalInformationSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ais.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{approval_information.Label}
	default:
		err = fmt.Errorf("ent: ApprovalInformationSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ais *ApprovalInformationSelect) BoolX(ctx context.Context) bool {
	v, err := ais.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ais *ApprovalInformationSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ais.sqlQuery().Query()
	if err := ais.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ais *ApprovalInformationSelect) sqlQuery() sql.Querier {
	selector := ais.sql
	selector.Select(selector.Columns(ais.fields...)...)
	return selector
}
