// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GodFather-server/ent/predicate"
	"GodFather-server/ent/product_order"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductOrderDelete is the builder for deleting a Product_order entity.
type ProductOrderDelete struct {
	config
	hooks    []Hook
	mutation *ProductOrderMutation
}

// Where adds a new predicate to the ProductOrderDelete builder.
func (pod *ProductOrderDelete) Where(ps ...predicate.Product_order) *ProductOrderDelete {
	pod.mutation.predicates = append(pod.mutation.predicates, ps...)
	return pod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pod *ProductOrderDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pod.hooks) == 0 {
		affected, err = pod.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductOrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pod.mutation = mutation
			affected, err = pod.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pod.hooks) - 1; i >= 0; i-- {
			mut = pod.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pod.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pod *ProductOrderDelete) ExecX(ctx context.Context) int {
	n, err := pod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pod *ProductOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: product_order.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: product_order.FieldID,
			},
		},
	}
	if ps := pod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pod.driver, _spec)
}

// ProductOrderDeleteOne is the builder for deleting a single Product_order entity.
type ProductOrderDeleteOne struct {
	pod *ProductOrderDelete
}

// Exec executes the deletion query.
func (podo *ProductOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := podo.pod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{product_order.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (podo *ProductOrderDeleteOne) ExecX(ctx context.Context) {
	podo.pod.ExecX(ctx)
}
