// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GodFather-server/ent/predicate"
	"GodFather-server/ent/product_order"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductOrderQuery is the builder for querying Product_order entities.
type ProductOrderQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.Product_order
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductOrderQuery builder.
func (poq *ProductOrderQuery) Where(ps ...predicate.Product_order) *ProductOrderQuery {
	poq.predicates = append(poq.predicates, ps...)
	return poq
}

// Limit adds a limit step to the query.
func (poq *ProductOrderQuery) Limit(limit int) *ProductOrderQuery {
	poq.limit = &limit
	return poq
}

// Offset adds an offset step to the query.
func (poq *ProductOrderQuery) Offset(offset int) *ProductOrderQuery {
	poq.offset = &offset
	return poq
}

// Order adds an order step to the query.
func (poq *ProductOrderQuery) Order(o ...OrderFunc) *ProductOrderQuery {
	poq.order = append(poq.order, o...)
	return poq
}

// First returns the first Product_order entity from the query.
// Returns a *NotFoundError when no Product_order was found.
func (poq *ProductOrderQuery) First(ctx context.Context) (*Product_order, error) {
	nodes, err := poq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{product_order.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (poq *ProductOrderQuery) FirstX(ctx context.Context) *Product_order {
	node, err := poq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Product_order ID from the query.
// Returns a *NotFoundError when no Product_order ID was found.
func (poq *ProductOrderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = poq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{product_order.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (poq *ProductOrderQuery) FirstIDX(ctx context.Context) int {
	id, err := poq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Product_order entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one Product_order entity is not found.
// Returns a *NotFoundError when no Product_order entities are found.
func (poq *ProductOrderQuery) Only(ctx context.Context) (*Product_order, error) {
	nodes, err := poq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{product_order.Label}
	default:
		return nil, &NotSingularError{product_order.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (poq *ProductOrderQuery) OnlyX(ctx context.Context) *Product_order {
	node, err := poq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Product_order ID in the query.
// Returns a *NotSingularError when exactly one Product_order ID is not found.
// Returns a *NotFoundError when no entities are found.
func (poq *ProductOrderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = poq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = &NotSingularError{product_order.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (poq *ProductOrderQuery) OnlyIDX(ctx context.Context) int {
	id, err := poq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Product_orders.
func (poq *ProductOrderQuery) All(ctx context.Context) ([]*Product_order, error) {
	if err := poq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return poq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (poq *ProductOrderQuery) AllX(ctx context.Context) []*Product_order {
	nodes, err := poq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Product_order IDs.
func (poq *ProductOrderQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := poq.Select(product_order.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (poq *ProductOrderQuery) IDsX(ctx context.Context) []int {
	ids, err := poq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (poq *ProductOrderQuery) Count(ctx context.Context) (int, error) {
	if err := poq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return poq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (poq *ProductOrderQuery) CountX(ctx context.Context) int {
	count, err := poq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (poq *ProductOrderQuery) Exist(ctx context.Context) (bool, error) {
	if err := poq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return poq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (poq *ProductOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := poq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (poq *ProductOrderQuery) Clone() *ProductOrderQuery {
	if poq == nil {
		return nil
	}
	return &ProductOrderQuery{
		config:     poq.config,
		limit:      poq.limit,
		offset:     poq.offset,
		order:      append([]OrderFunc{}, poq.order...),
		predicates: append([]predicate.Product_order{}, poq.predicates...),
		// clone intermediate query.
		sql:  poq.sql.Clone(),
		path: poq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductOrder.Query().
//		GroupBy(product_order.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (poq *ProductOrderQuery) GroupBy(field string, fields ...string) *ProductOrderGroupBy {
	group := &ProductOrderGroupBy{config: poq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := poq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return poq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ProductOrder.Query().
//		Select(product_order.FieldName).
//		Scan(ctx, &v)
//
func (poq *ProductOrderQuery) Select(field string, fields ...string) *ProductOrderSelect {
	poq.fields = append([]string{field}, fields...)
	return &ProductOrderSelect{ProductOrderQuery: poq}
}

func (poq *ProductOrderQuery) prepareQuery(ctx context.Context) error {
	for _, f := range poq.fields {
		if !product_order.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if poq.path != nil {
		prev, err := poq.path(ctx)
		if err != nil {
			return err
		}
		poq.sql = prev
	}
	return nil
}

func (poq *ProductOrderQuery) sqlAll(ctx context.Context) ([]*Product_order, error) {
	var (
		nodes   = []*Product_order{}
		withFKs = poq.withFKs
		_spec   = poq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, product_order.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &Product_order{config: poq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, poq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (poq *ProductOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := poq.querySpec()
	return sqlgraph.CountNodes(ctx, poq.driver, _spec)
}

func (poq *ProductOrderQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := poq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (poq *ProductOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   product_order.Table,
			Columns: product_order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: product_order.FieldID,
			},
		},
		From:   poq.sql,
		Unique: true,
	}
	if fields := poq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product_order.FieldID)
		for i := range fields {
			if fields[i] != product_order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := poq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := poq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := poq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := poq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, product_order.ValidColumn)
			}
		}
	}
	return _spec
}

func (poq *ProductOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(poq.driver.Dialect())
	t1 := builder.Table(product_order.Table)
	selector := builder.Select(t1.Columns(product_order.Columns...)...).From(t1)
	if poq.sql != nil {
		selector = poq.sql
		selector.Select(selector.Columns(product_order.Columns...)...)
	}
	for _, p := range poq.predicates {
		p(selector)
	}
	for _, p := range poq.order {
		p(selector, product_order.ValidColumn)
	}
	if offset := poq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := poq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductOrderGroupBy is the group-by builder for Product_order entities.
type ProductOrderGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pogb *ProductOrderGroupBy) Aggregate(fns ...AggregateFunc) *ProductOrderGroupBy {
	pogb.fns = append(pogb.fns, fns...)
	return pogb
}

// Scan applies the group-by query and scans the result into the given value.
func (pogb *ProductOrderGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pogb.path(ctx)
	if err != nil {
		return err
	}
	pogb.sql = query
	return pogb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pogb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pogb.fields) > 1 {
		return nil, errors.New("ent: ProductOrderGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) StringsX(ctx context.Context) []string {
	v, err := pogb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pogb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) StringX(ctx context.Context) string {
	v, err := pogb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pogb.fields) > 1 {
		return nil, errors.New("ent: ProductOrderGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) IntsX(ctx context.Context) []int {
	v, err := pogb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pogb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) IntX(ctx context.Context) int {
	v, err := pogb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pogb.fields) > 1 {
		return nil, errors.New("ent: ProductOrderGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pogb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pogb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pogb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pogb.fields) > 1 {
		return nil, errors.New("ent: ProductOrderGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pogb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pogb *ProductOrderGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pogb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pogb *ProductOrderGroupBy) BoolX(ctx context.Context) bool {
	v, err := pogb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pogb *ProductOrderGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pogb.fields {
		if !product_order.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pogb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pogb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pogb *ProductOrderGroupBy) sqlQuery() *sql.Selector {
	selector := pogb.sql
	columns := make([]string, 0, len(pogb.fields)+len(pogb.fns))
	columns = append(columns, pogb.fields...)
	for _, fn := range pogb.fns {
		columns = append(columns, fn(selector, product_order.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(pogb.fields...)
}

// ProductOrderSelect is the builder for selecting fields of ProductOrder entities.
type ProductOrderSelect struct {
	*ProductOrderQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pos *ProductOrderSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pos.prepareQuery(ctx); err != nil {
		return err
	}
	pos.sql = pos.ProductOrderQuery.sqlQuery(ctx)
	return pos.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pos *ProductOrderSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pos.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pos.fields) > 1 {
		return nil, errors.New("ent: ProductOrderSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pos *ProductOrderSelect) StringsX(ctx context.Context) []string {
	v, err := pos.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pos.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pos *ProductOrderSelect) StringX(ctx context.Context) string {
	v, err := pos.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pos.fields) > 1 {
		return nil, errors.New("ent: ProductOrderSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pos *ProductOrderSelect) IntsX(ctx context.Context) []int {
	v, err := pos.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pos.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pos *ProductOrderSelect) IntX(ctx context.Context) int {
	v, err := pos.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pos.fields) > 1 {
		return nil, errors.New("ent: ProductOrderSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pos *ProductOrderSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pos.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pos.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pos *ProductOrderSelect) Float64X(ctx context.Context) float64 {
	v, err := pos.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pos.fields) > 1 {
		return nil, errors.New("ent: ProductOrderSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pos *ProductOrderSelect) BoolsX(ctx context.Context) []bool {
	v, err := pos.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pos *ProductOrderSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pos.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{product_order.Label}
	default:
		err = fmt.Errorf("ent: ProductOrderSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pos *ProductOrderSelect) BoolX(ctx context.Context) bool {
	v, err := pos.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pos *ProductOrderSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pos.sqlQuery().Query()
	if err := pos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pos *ProductOrderSelect) sqlQuery() sql.Querier {
	selector := pos.sql
	selector.Select(selector.Columns(pos.fields...)...)
	return selector
}
