// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GodFather-server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	approval_informationFields := schema.Approval_information{}.Fields()
	_ = approval_informationFields
	userFields := schema.User{}.Fields()
	_ = userFields
}
