// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Approval_information is the predicate function for approval_information builders.
type Approval_information func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Product_order is the predicate function for product_order builders.
type Product_order func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
